name: Android Beta APK build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Dar permiso a Gradle
        run: chmod +x gradlew
          
      - name: Compilar APK
        run: ./gradlew assembleDebug
          
      - name: Mostrar rutas generadas
        run: find . -name "*.apk" -type f
          
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: DCtune-Beta-APK
          path: androbd/build/outputs/apk/debug/
