name: DCcecuelm327 — Release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compilar APK Release
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: DCcecuelm327-Release
          path: androbd/build/outputs/apk/release/androbd-release.apk
